# Generated by Django 3.1.2 on 2020-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='phone')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='birth date')),
                ('gender', models.IntegerField(blank=True, default=-1, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_store', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
                ('date_activate', models.DateField(blank=True, null=True, verbose_name='date of activate')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
